# Generated by Django 4.2.7 on 2023-11-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(),
        ),
    ]
